name: "CI"
on:
  pull_request:
  push:
jobs:
  tests-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix build
    - run: nix flake check
  tests-darwin:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix build
    - run: nix flake check
    - run: |
        system=$(nix build --no-link --print-out-paths .#checks.x86_64-darwin.integration)
        ${system}/activate-user
        sudo ${system}/activate
    - run: sudo /run/current-system/sw/bin/agenix-integration
